=== w3c-ccg/traceability-vocab/versions/v0.1.0/schemas/MillTestReportCertificate.json
{
  "$id": "https://w3id.org/traceability/schemas/MillTestReportCertificate.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"MillTestReportCertificate\", \"@id\": \"https://w3id.org/traceability#MillTestReportCertificate\"}",
  "title": "Mill Test Report Certificate",
  "description": "Certifications made by a manufacturer of a metal product.",
  "type": "object",
  "properties": {
    "@context": {
      "type": "array",
      "const": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/traceability/v1"
      ]
    },
    "type": {
      "type": "array",
      "const": ["VerifiableCredential", "MillTestReportCertificate"]
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "issuanceDate": {
      "type": "string"
    },
    "issuer": {
      "type": "object"
    },
    "credentialSubject": {
      "type": "object"
    },
    "proof": {
      "type": "object"
    },
    "relatedLink": {
      "title": "Related Link",
      "description": "Links related to this verifiable credential",
      "type": "array",
      "items": {
        "$ref": "https://w3id.org/traceability/schemas/LinkRole.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [],
  "examples": []
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/MillTestReportCertificate/good.json
[
  {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "https://example.com/credential/123",
    "type": [
      "VerifiableCredential",
      "MillTestReportCertificate"
    ],
    "name": "Certified Mill Test Report",
    "description": "This document includes recommended mill certificate fields.",
    "relatedLink": [
      {
        "type": [
          "LinkRole"
        ],
        "target": "https://www.example.com/template/123",
        "linkRelationship": "templateLink"
      }
    ],
    "issuanceDate": "2019-12-11T03:50:55Z",
    "issuer": {
      "id": "did:example:123",
      "type": "Organization",
      "name": "Considine, Conn and Halvorson",
      "description": "Managed zero administration hardware",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "9140 Quitzon Inlet",
        "addressLocality": "West Keirafort",
        "addressRegion": "Alaska",
        "postalCode": "57315",
        "addressCountry": "Suriname"
      },
      "email": "Haylee.Klocko@example.org",
      "phoneNumber": "555-732-7621",
      "faxNumber": "555-670-2905"
    },
    "credentialSubject": {
      "type": [
        "MillTestReport"
      ],
      "manufacturer": {
        "type": [
          "Organization"
        ],
        "name": "Douglas LLC",
        "description": "Up-sized value-added solution",
        "address": {
          "type": [
            "PostalAddress"
          ],
          "streetAddress": "4995 Eloise Via",
          "addressLocality": "Berttown",
          "addressRegion": "Tennessee",
          "postalCode": "95293",
          "addressCountry": "Sweden"
        },
        "email": "Opal_Robel@example.net",
        "phoneNumber": "555-947-3055",
        "faxNumber": "555-740-2980"
      },
      "product": {
        "type": [
          "SteelProduct"
        ],
        "heatNumber": "71844",
        "specification": "ASTM-78418",
        "grade": "52325",
        "originalCountryOfMeltAndPour": "Saint Pierre and Miquelon",
        "inspection": {
          "type": [
            "InspectionReport"
          ],
          "observation": [
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "ChemicalProperty"
                ],
                "name": "Francium"
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "21.838",
                "unitCode": "P1"
              }
            },
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "ChemicalProperty"
                ],
                "name": "Lanthanum"
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "24.473",
                "unitCode": "P1"
              }
            },
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "ChemicalProperty"
                ],
                "name": "Sulfur"
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "22.791",
                "unitCode": "P1"
              }
            },
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "ChemicalProperty"
                ],
                "name": "Lutetium"
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "13.489",
                "unitCode": "P1"
              }
            },
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "ChemicalProperty"
                ],
                "name": "Titanium"
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "17.409",
                "unitCode": "P1"
              }
            },
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "MechanicalProperty"
                ],
                "identifier": "ISO 3738",
                "name": "Rockwell Hardness Test (Scale A)",
                "description": "The Rockwell hardness test is an empirical indentation hardness test that can provide useful information about metallic materials."
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "00.00",
                "unitCode": "UNKNOWN"
              }
            }
          ]
        }
      },
      "purchase": {
        "type": [
          "Purchase"
        ],
        "customer": {
          "type": [
            "Person"
          ],
          "email": "Oleta_Mayer@example.com",
          "phoneNumber": "555-177-8328"
        }
      },
      "shipment": {
        "type": [
          "ParcelDelivery"
        ],
        "deliveryAddress": {
          "type": [
            "PostalAddress"
          ],
          "organizationName": "Dickens, Collins and Heller",
          "streetAddress": "91784 Raynor Flat",
          "addressLocality": "Port Mckenna",
          "addressRegion": "Nebraska",
          "postalCode": "52403-6456",
          "addressCountry": "India"
        },
        "originAddress": {
          "type": [
            "PostalAddress"
          ],
          "organizationName": "Wehner - Lubowitz",
          "streetAddress": "283 O'Kon Loop",
          "addressLocality": "Tremblayshire",
          "addressRegion": "Maryland",
          "postalCode": "97456-6799",
          "addressCountry": "Ecuador"
        },
        "deliveryMethod": "Truck transport",
        "trackingNumber": "244623827627"
      }
    }
  },
  {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "https://example.com/credential/123",
    "type": [
      "VerifiableCredential",
      "MillTestReportCertificate"
    ],
    "name": "Certified Mill Test Report",
    "description": "This document includes recommended mill certificate fields.",
    "relatedLink": [
      {
        "type": [
          "LinkRole"
        ],
        "target": "https://www.example.com/template/123",
        "linkRelationship": "templateLink"
      }
    ],
    "issuanceDate": "2019-12-11T03:50:55Z",
    "issuer": {
      "id": "did:example:123",
      "type": "Organization",
      "name": "Schaden - Little",
      "description": "Digitized hybrid migration",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "436 Lesch Views",
        "addressLocality": "New Vidatown",
        "addressRegion": "Montana",
        "postalCode": "76443",
        "addressCountry": "Liechtenstein"
      },
      "email": "Rebecca.Kunze@example.org",
      "phoneNumber": "555-466-1566",
      "faxNumber": "555-468-8507"
    },
    "credentialSubject": {
      "type": [
        "MillTestReport"
      ],
      "manufacturer": {
        "type": [
          "Organization"
        ],
        "name": "Gleason and Sons",
        "description": "Mandatory systematic algorithm",
        "address": {
          "type": [
            "PostalAddress"
          ],
          "streetAddress": "263 Jacobson Prairie",
          "addressLocality": "Sylvesterland",
          "addressRegion": "New York",
          "postalCode": "73329-4828",
          "addressCountry": "Malaysia"
        },
        "email": "Olaf.Blanda@example.org",
        "phoneNumber": "555-254-4136",
        "faxNumber": "555-343-2188"
      },
      "product": {
        "type": [
          "SteelProduct"
        ],
        "heatNumber": "95392",
        "specification": "ASTM-98424",
        "grade": "81420",
        "originalCountryOfMeltAndPour": "South Georgia and the South Sandwich Islands",
        "inspection": {
          "type": [
            "InspectionReport"
          ],
          "observation": [
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "ChemicalProperty"
                ],
                "name": "Niobium"
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "17.680",
                "unitCode": "P1"
              }
            },
            {
              "type": [
                "Observation"
              ],
              "property": {
                "type": [
                  "MechanicalProperty"
                ],
                "identifier": "ISO 1352",
                "name": "Torque-controlled fatigue testing",
                "description": "ISO 1352:2011 specifies the conditions for performing torsional, constant-amplitude, nominally elastic stress fatigue tests on metallic specimens without deliberately introducing stress concentrations. The tests are carried out at ambient temperature (ideally at between 10 째C and 35 째C) in air by applying a pure couple to the specimen about its longitudinal axis."
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "00.00",
                "unitCode": "UNKNOWN"
              }
            },
            {
              "type": [
