=== w3c-ccg/traceability-vocab/packages/traceability-schemas/schemas/MechanicalProperty.json
{
  "$id": "https://w3id.org/traceability/schemas/MechanicalProperty.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"MechanicalProperty\", \"@id\": \"https://w3id.org/traceability#MechanicalProperty\"}",
  "title": "Mechanical Property",
  "description": "A property, used to indicate attributes and relationships of some Thing; equivalent to rdf:Property.",
  "type": "object",
  "properties": {
    "@context": {
      "type": "array"
    },
    "type": {
      "oneOf": [
          { "type": "string" },
          { "type": "array"}
      ]
  },
    "identifier": {
      "$comment": "{\"term\": \"identifier\", \"@id\": \"https://schema.org/identifier\"}",
      "title": "Property Identifier",
      "description": "Identifiers for a property.",
      "type": "string"
    },
    "name": {
      "$comment": "{\"term\": \"name\", \"@id\": \"https://schema.org/name\"}",
      "title": "Property Name",
      "description": "The name of the item.",
      "type": "string"
    },
    "description": {
      "$comment": "{\"term\": \"description\", \"@id\": \"https://schema.org/description\"}",
      "title": "Property Description",
      "description": "The description of the item.",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "examples": []
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/MeasuredProperty/good.json
[
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "MechanicalProperty",
    "identifier": "ISO 1352",
    "name": "Torque-controlled fatigue testing",
    "description": "ISO 1352:2011 specifies the conditions for performing torsional, constant-amplitude, nominally elastic stress fatigue tests on metallic specimens without deliberately introducing stress concentrations. The tests are carried out at ambient temperature (ideally at between 10 째C and 35 째C) in air by applying a pure couple to the specimen about its longitudinal axis."
  },
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "MechanicalProperty",
    "identifier": "ISO 1352",
    "name": "Torque-controlled fatigue testing",
    "description": "ISO 1352:2011 specifies the conditions for performing torsional, constant-amplitude, nominally elastic stress fatigue tests on metallic specimens without deliberately introducing stress concentrations. The tests are carried out at ambient temperature (ideally at between 10 째C and 35 째C) in air by applying a pure couple to the specimen about its longitudinal axis."
  },
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "MechanicalProperty",
    "identifier": "ISO 180",
    "name": "Izod Impact Strength Test",
    "description": "ISO 180 defines the method used for pendulums to determine the impact resistance of a plastic specimen when supported in a cantilever configuration. Test results are used to evaluate the resilience of materials, typically plastics."
  }
]
