=== w3c-ccg/traceability-vocab/packages/traceability-schemas/schemas/NaturalGasProduct.json
{
    "$id": "https://w3id.org/traceability/schemas/NaturalGasProduct.json",
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$comment": "{\"term\": \"NaturalGasProduct\", \"@id\": \"https://w3id.org/traceability#NaturalGasProduct\"}",
    "title": "Natural Gas Product",
    "description": "Tombstone information regarding a natural gas product",
    "type": "object",
    "properties": {
        "@context": {
            "type": "array"
        },
        "id": {
            "type": "string"
        },
        "issuanceDate": {
            "type": "string"
        },
        "credentialSubject": {
            "type": "object"
        },
        "issuer": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "object"
                }
            ]
        },
        "type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array"
                }
            ]
        },
        "product": {
            "$comment": "{\"term\": \"product\", \"@id\": \"https://www.gs1.org/voc/Product\"}",
            "title": "Product",
            "description": "Product details as outlined in the Product.json schema",
            "$ref": "https://w3id.org/traceability/schemas/Product.json"
        },
        "facility": {
            "$comment": "{\"term\": \"facility\", \"@id\": \"https://www.gs1.org/voc/Place\"}",
            "title": "Manufacture Facility",
            "description": "Information on the manufacture facility.",
            "$ref": "https://w3id.org/traceability/schemas/Place.json"
        },
        "UWI": {
            "$comment": "{\"term\": \"UWI\", \"@id\": \"https://schema.org/identifier?1\"}",
            "title": "Unique Well Identifier",
            "description": "Unique Well Identifier used for individual well identification.",
            "type": "string"
        },
        "HSCode": {
            "$comment": "{\"term\": \"HSCode\", \"@id\": \"https://w3id.org/identifier?2\"}",
            "title": "HSCode",
            "description": "Defines the Harmonized System Code for the Commodity",
            "type": "string"
        },
        "productionDate": {
            "$comment": "{\"term\": \"productionDate\", \"@id\": \"https://schema.org/DateTime#v2\"}",
            "title": "Production Date",
            "description": "Date when the product was created",
            "type": "string"
        },
        "observation": {
            "$comment": "{\"term\": \"observation\", \"@id\": \"https://w3id.org/traceability#observation\"}",
            "title": "Observation List",
            "description": "List of observations as seen and specified in the Inspection Report schema https://w3id.org/traceability?#InspectionReport",
            "type": "array",
            "items": {
                "$ref": "https://w3id.org/traceability/schemas/Observation.json"
            }
        }
    },
    "additionalProperties": false,
    "examples": []
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/LinkRole/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "LinkRole",
    "target": "https://example.com/related/link/123",
    "linkRelationship": "alternate"
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/CommercialInvoiceCertificate/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "https://example.com/credential/123",
    "type": [
      "VerifiableCredential",
      "CommercialInvoiceCertificate"
    ],
    "name": "Commercial Invoice Certificate",
    "description": "This document includes recommended commercial invoice fields.",
    "relatedLink": [
      {
        "type": [
          "LinkRole"
        ],
        "target": "https://www.example.com/template/123",
        "linkRelationship": "templateLink"
      },
      {
        "type": [
          "LinkRole"
        ],
        "target": "did:example:789",
        "linkRelationship": "billOfLadingLink"
      },
      {
        "type": [
          "LinkRole"
        ],
        "target": "https://www.example.com/credentials/123",
        "linkRelationship": "millTestReportLink"
      }
    ],
    "issuanceDate": "2019-12-11T03:50:55Z",
    "issuer": {
      "id": "did:example:123",
      "type": "Organization",
      "name": "Conroy Inc",
      "description": "Reverse-engineered user-facing process improvement",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "832 Lehner Row",
        "addressLocality": "Schimmeltown",
        "addressRegion": "Wyoming",
        "postalCode": "26980-2000",
        "addressCountry": "Rwanda"
      },
      "email": "Maeve_Schowalter84@example.net",
      "phoneNumber": "555-407-8507",
      "faxNumber": "555-669-7664"
    },
    "credentialSubject": {
      "type": [
        "CommercialInvoice"
      ],
      "portOfEntry": {
        "type": [
          "PostalAddress"
        ],
        "addressLocality": "Seatle",
        "addressRegion": "Washington",
        "addressCountry": "USA"
      },
      "destinationCountry": "MEX",
      "purchaseDate": "2021-02-21",
      "customer": {
        "type": [
          "Organization"
        ],
        "address": {
          "type": [
            "PostalAddress"
          ],
          "organizationName": "Generic Motors of America",
          "streetAddress": "12 Generic Motors Dr",
          "addressLocality": "Detroit",
          "addressRegion": "Michigain",
          "postalCode": "48232-5170",
          "addressCountry": "USA"
        }
      },
      "provider": {
        "type": [
          "Organization"
        ],
        "address": {
          "type": [
            "PostalAddress"
          ],
          "organizationName": "Aishi Metal Shinzo Co., Ltd.",
          "streetAddress": "1651, Shimonakano, Yoshida",
          "addressLocality": "Tsubame-shi",
          "addressRegion": "Niigata-ken",
          "postalCode": "959-0215",
          "addressCountry": "Japan"
        }
      },
      "totalPaymentDue": {
        "type": [
          "PriceSpecification"
        ],
        "price": 150000,
        "priceCurrency": "USD"
      },
      "merchandise": [
        {
          "type": [
            "Product"
          ],
          "manufacturer": {
            "type": [
              "Organization"
            ]
          },
          "description": "UNS S30400 chromium-nickel stainless steel rolls.",
          "weight": {
            "type": [
              "QuantitativeValue"
            ],
            "unitCode": "lbs",
            "value": "10000"
          },
          "quantity": "5",
          "priceSpecification": {
            "type": [
              "PriceSpecification"
            ],
            "price": 10000,
            "priceCurrency": "USD"
          }
        },
        {
          "type": [
            "Product"
          ],
          "manufacturer": {
            "type": [
              "Organization"
            ]
          },
          "description": "Galvalannealed ASTM A-653 zinc-iron alloy-coated steel sheets.",
          "weight": {
            "type": [
              "QuantitativeValue"
            ],
            "unitCode": "lbs",
            "value": "20000"
          },
          "quantity": "10",
          "priceSpecification": {
            "type": [
              "PriceSpecification"
            ],
            "price": 10000,
            "priceCurrency": "USD"
          }
        }
      ]
    }
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/EcommerceWayBillCommodityContent/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "EcommerceWayBillCommodityContent",
    "wayBillGrouping": [
      {
        "type": "EcommerceWayBillCommodityGroup",
        "commodityItemNumber": "ivec7oe02okb",
        "natureQuantityOfGoods": "A lot of laptops that way a lot",
        "totalsCommodityGroup": {
          "type": "EcommerceWayBillTotals",
          "totalPieces": 855,
          "weight": 65183,
          "chargeableWeight": 58664.700000000004,
          "weightUnit": "lb",
          "rateCharge": 0.10401485049782919,
          "totalRateCharge": {
            "type": "PriceSpecification",
            "price": 6102,
            "priceCurrency": "PKR"
          }
        }
      }
    ],
    "totalsCommodityContent": {
      "type": "EcommerceWayBillTotals",
      "totalPieces": 96,
      "weight": 392939,
      "chargeableWeight": 353645.10000000003,
      "weightUnit": "kg",
      "rateCharge": 0.002304570316399124,
      "totalRateCharge": {
        "type": "PriceSpecification",
        "price": 815,
        "priceCurrency": "CNY"
      }
    }
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/EcommercePackageRegistrationCredential/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "EcommercePackageRegistrationCredential",
    "trackingID": "978429431398",
    "packageItems": [
      {
        "type": "EcommercePackageItem",
        "productReceiptID": "https://vc.example.com/?queryID=0xCCEF62556D6E09E1409c08C0AcE0BB6650fc88cF0b16bfc5AD28bc41299C3B44",
        "packingListID": "https://vc.example.com/?queryID=0x645B1E124917dD61647Ae1DaA9A7a8fbc34c4B6AE3c3A577882e31C0c87fB45e",
        "orderID": "https://vc.example.com/?queryID=AB06f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a",
        "productInOrder": [
          "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58599e"
        ]
      }
    ],
    "certificateName": "ACME Carrier Ecommerce Package Registration Certificate"
  }
}

=== w3c-ccg/traceability-vocab/packages/generate-examples/src/__fixture__/phyto.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": ["VerifiableCredential"],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
   "credentialSubject": {
      "id": "did:example:123",
      "type": "Phytosanitary",
      "facility": {
         "type": "Place",
         "globalLocationNumber": "3857367970333",
         "geo": {
            "type": "GeoCoordinates",
            "latitude": "-86.0919",
            "longitude": "-135.9487"
         },
         "address": {
            "type": "PostalAddress",
            "organizationName": "Balistreri - Heathcote",
            "streetAddress": "745 Luigi Station",
            "addressLocality": "North Gregoryland",
            "addressRegion": "Illinois",
            "postalCode": "20685",
            "addressCountry": "USA"
         }
      },
      "inspector": {
         "type": "Inspector",
         "person": {
            "type": "Person",
            "firstName": "Alysha",
            "lastName": "Denesik",
            "email": "Earlene.Grant81@example.net",
            "phoneNumber": "555-184-8046",
            "worksFor": {
               "type": "Organization",
               "name": "Block, Schinner and Lemke",
               "description": "Specializing in Agriculture Inspections",
               "address": {
                  "type": "PostalAddress",
                  "streetAddress": "214 Schmeler Common",
                  "addressLocality": "East Brownhaven",
                  "addressRegion": "Florida",
                  "postalCode": "25831",
                  "addressCountry": "USA"
               },
               "email": "Elza.Schoen21@example.net",
               "phoneNumber": "555-113-7997"
            },
            "jobTitle": "Internal Inspection Facilitator"
         },
         "qualification": [
            {
               "type": "Qualification",
               "qualificationCategory": "Phytosanitary Inspector",
               "qualificationValue": "Director"
            }
         ]
      },
      "shipment": {
         "type": "ParcelDelivery",
         "deliveryAddress": {
            "type": "PostalAddress",
            "organizationName": "Target",
            "streetAddress": "8972 D'Amore Ways",
            "addressLocality": "East Brandy",
            "addressRegion": "Kentucky",
            "postalCode": "11185-7827",
            "addressCountry": "USA"
         },
         "originAddress": {
            "type": "PostalAddress",
            "organizationName": "Poppy's Produce",
            "streetAddress": "81859 Kira Isle",
            "addressLocality": "Teaganfort",
            "addressRegion": "Maryland",
            "postalCode": "07902",
            "addressCountry": "USA"
         },
         "deliveryMethod": "Truck transport",
         "trackingNumber": "41570762785"
      },
      "applicant": {
         "type": "Person",
         "firstName": "Orval",
         "lastName": "Kertzmann",
         "email": "Flavie_Dickinson89@example.com",
         "phoneNumber": "555-124-1797",
         "worksFor": {
            "type": "Organization",
            "name": "Vandervort - Williamson",
            "description": "Expanded encompassing frame",
            "address": {
               "type": "PostalAddress",
               "organizationName": "Poppy's Produce",
               "streetAddress": "81859 Kira Isle",
               "addressLocality": "Teaganfort",
               "addressRegion": "Maryland",
               "postalCode": "07902",
               "addressCountry": "USA"
            },
            "email": "Willa18@example.org",
            "phoneNumber": "555-915-2859"
         },
         "jobTitle": "Export Manager"
      },
      "inspectionDate": "2020-03-15",
      "inspectionType": "Food Safety",
      "observation": [
         {
            "type": "Observation",
            "property": {
               "type": "MechanicalProperty",
               "identifier": "ISO 1352",
               "name": "Torque-controlled fatigue testing",
               "description": "ISO 1352:2011 specifies the conditions for performing torsional, constant-amplitude, nominally elastic stress fatigue tests on metallic specimens without deliberately introducing stress concentrations. The tests are carried out at ambient temperature (ideally at between 10 °C and 35 °C) in air by applying a pure couple to the specimen about its longitudinal axis."
            },
            "measurement": {
               "type": "MeasuredValue",
               "value": "00.00",
               "unitCode": "UNKNOWN"
            }
         }
      ],
      "certificateNumber": "3403816816",
      "plantOrg": {
         "type": "Organization",
         "name": "Lind LLC",
         "description": "Plant Services",
         "address": {
            "type": "PostalAddress",
            "streetAddress": "075 Jennings Haven",
            "addressLocality": "Millsfort",
            "addressRegion": "Connecticut",
            "postalCode": "58116",
            "addressCountry": "USA"
         },
         "email": "Fay9@example.org",
         "phoneNumber": "555-605-4698"
      },
      "distinguishingMarks": "Some fading and slight packaging damage on the bottom of the package.",
      "portOfEntry": {
         "type": "Place",
         "address": {
            "type": "PostalAddress",
            "addressLocality": "Treutelmouth",
            "addressRegion": "South Carolina"
         }
      },
      "additionalDeclaration": "Voluptas quia sed voluptatem quaerat.",
      "disinfectionDate": "2021-02-22",
      "disinfectionTreatment": "Fumigant - Phosphine",
      "disinfectionChemical": "Methyl Bromide",
      "disinfectionDuration": "144 minutes",
      "disinfectionTemperature": {
         "type": "MeasuredValue",
         "value": "20",
         "unitCode": "Celsius"
      },
      "disinfectionConcentration": {
         "type": "MeasuredValue",
         "value": "10",
         "unitCode": "Percent"
      },
      "signatureDate": "2021-03-12"
   }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/EcommerceOrderRegistrationCredential/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "EcommerceOrderRegistrationCredential",
    "orderID": "Order#455",
    "productInOrder": [
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a"
    ],
    "certificateName": "ACME Ecommerce Order Registration Certificate"
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/LEIregistration/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "LEIregistration",
    "initialRegistrationDate": "2020-01-01",
    "lastUpdateDate": "2020-01-01",
    "status": "IN PROGRESS",
    "nextRenewalDate": "2021-02-02",
    "managingLou": "YAYYFCJVDMNRLNXMYVJT",
    "validationSources": "PARTIALLY_CORROBORATED",
    "validationAuthority": [
      {
        "type": "LEIauthority",
        "validationAuthorityID": "RA000003",
        "otherValidationAuthorityID": "Y9IF2QMC",
        "validationAuthorityEntityID": "CBUAFH666HRP91R072BJ"
      }
    ]
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/InspectionReport/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "InspectionReport",
    "observation": [
      {
        "type": "Observation",
        "property": {
          "type": "ChemicalProperty",
          "name": "Europium",
          "formula": "Eu",
          "inchi": "InChI=1S/Eu",
          "inchikey": "OGPBJKLSAFTDLK-UHFFFAOYSA-N"
        },
        "measurement": {
          "type": "MeasuredValue",
          "value": "100.00",
          "unitCode": "P1"
        }
      }
    ]
  }
}
