=== w3c-ccg/traceability-vocab/packages/traceability-schemas/schemas/NaturalGasProduct.json
{
    "$id": "https://w3id.org/traceability/schemas/NaturalGasProduct.json",
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$comment": "{\"term\": \"NaturalGasProduct\", \"@id\": \"https://w3id.org/traceability#NaturalGasProduct\"}",
    "title": "Natural Gas Product",
    "description": "Tombstone information regarding a natural gas product",
    "type": "object",
    "properties": {
        "@context": {
            "type": "array"
        },
        "id": {
            "type": "string"
        },
        "issuanceDate": {
            "type": "string"
        },
        "credentialSubject": {
            "type": "object"
        },
        "issuer": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "object"
                }
            ]
        },
        "type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array"
                }
            ]
        },
        "product": {
            "$comment": "{\"term\": \"product\", \"@id\": \"https://www.gs1.org/voc/Product\"}",
            "title": "Product",
            "description": "Product details as outlined in the Product.json schema",
            "$ref": "https://w3id.org/traceability/schemas/Product.json"
        },
        "facility": {
            "$comment": "{\"term\": \"facility\", \"@id\": \"https://www.gs1.org/voc/Place\"}",
            "title": "Manufacture Facility",
            "description": "Information on the manufacture facility.",
            "$ref": "https://w3id.org/traceability/schemas/Place.json"
        },
        "UWI": {
            "$comment": "{\"term\": \"UWI\", \"@id\": \"https://schema.org/identifier?1\"}",
            "title": "Unique Well Identifier",
            "description": "Unique Well Identifier used for individual well identification.",
            "type": "string"
        },
        "HSCode": {
            "$comment": "{\"term\": \"HSCode\", \"@id\": \"https://w3id.org/identifier?2\"}",
            "title": "HSCode",
            "description": "Defines the Harmonized System Code for the Commodity",
            "type": "string"
        },
        "productionDate": {
            "$comment": "{\"term\": \"productionDate\", \"@id\": \"https://schema.org/DateTime#v2\"}",
            "title": "Production Date",
            "description": "Date when the product was created",
            "type": "string"
        },
        "observation": {
            "$comment": "{\"term\": \"observation\", \"@id\": \"https://w3id.org/traceability#observation\"}",
            "title": "Observation List",
            "description": "List of observations as seen and specified in the Inspection Report schema https://w3id.org/traceability?#InspectionReport",
            "type": "array",
            "items": {
                "$ref": "https://w3id.org/traceability/schemas/Observation.json"
            }
        }
    },
    "additionalProperties": false,
    "examples": []
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/CommodityType/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "CommodityType",
    "commodityDescription": "Flat-rolled products of iron or nonalloy steel, of a width of 600 mm or more, hot-rolled, not clad, plated or coated: Of a thickness of less than 3 mm High-strength steel.",
    "commodityCode": "7208.26.0030",
    "commodityCodeScheme": "HTS"
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/data/examples/credentials/intent-to-sell.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": ["VerifiableCredential"],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
     "id": "did:example:123",
     "type": "IntentToSell",
     "seller": {
        "type": "Person",
        "firstName": "Marcos",
        "lastName": "Osinski",
        "email": "Earnest_Hahn87@example.net",
        "phoneNumber": "555-814-3786",
        "worksFor": {
           "type": "Organization",
           "name": "Poppy's Produce",
           "description": "Providing the highest quality produce.",
           "address": {
              "type": "PostalAddress",
              "streetAddress": "30423 Scotty Crossroad",
              "addressLocality": "North Mireille",
              "addressRegion": "Rhode Island",
              "postalCode": "54011",
              "addressCountry": "USA"
           },
           "email": "Raegan_Boehm@example.org",
           "phoneNumber": "555-408-7603"
        },
        "jobTitle": "VP of Sales"
     },
     "purchaser": {
        "type": "Person",
        "firstName": "Kaycee",
        "lastName": "Pfeffer",
        "email": "Milton79@example.com",
        "phoneNumber": "555-396-9693",
        "worksFor": {
           "type": "Organization",
           "name": "Wolff Group",
           "description": "Grocery Store supplier",
           "address": {
              "type": "PostalAddress",
              "streetAddress": "65195 Nestor Glens",
              "addressLocality": "Jaskolskiview",
              "addressRegion": "Tennessee",
              "postalCode": "74088-3168",
              "addressCountry": "USA"
           },
           "email": "Leon.Stroman5@example.org",
           "phoneNumber": "555-456-2198"
        },
        "jobTitle": "Buyer"
     },
     "product": {
        "type": "Product",
        "manufacturer": {
           "type": "Organization",
           "name": "Poppy's Produce",
           "description": "Providing the Highest Quality Produce",
           "address": {
              "type": "PostalAddress",
              "streetAddress": "30423 Scotty Crossroad",
              "addressLocality": "North Mireille",
              "addressRegion": "Rhode Island",
              "postalCode": "54011",
              "addressCountry": "USA"
           },
           "email": "Declan.Veum@example.net",
           "phoneNumber": "555-315-7196"
        },
        "name": "Avocados",
        "description": "Delicious avocados",
        "sizeOrAmount": {
           "type": "QuantitativeValue",
           "unitCode": "hg/ha",
           "value": "4306"
        },
        "weight": {
           "type": "QuantitativeValue",
           "unitCode": "hg/ha",
           "value": "3076"
        },
        "sku": "556185142112"
     },
     "declarationDate": "2020-03-21",
     "sellByDate": "2021-06-30"
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/Observation/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "Observation",
    "property": {
      "type": "MechanicalProperty",
      "identifier": "ISO 180",
      "name": "Izod Impact Strength Test",
      "description": "ISO 180 defines the method used for pendulums to determine the impact resistance of a plastic specimen when supported in a cantilever configuration. Test results are used to evaluate the resilience of materials, typically plastics."
    },
    "measurement": {
      "type": "MeasuredValue",
      "value": "22.493",
      "unitCode": "B13"
    }
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/MeasuredValue/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "MeasuredValue",
    "value": "00.00",
    "unitCode": "UNKNOWN"
  }
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/EcommerceAdditionalProductCodeRegistrationCredential/credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.org/credentials/",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
  "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "EcommerceAdditionalProductCodeRegistrationCredential",
    "productVCid": "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a",
    "addProductCode": 25041880563367,
    "addProductCodeType": "UPC",
    "certificateName": "ACME Ecommerce Universal Product Code Product Registration Certificate"
  }
}

=== w3c-ccg/traceability-vocab/packages/generate-examples/src/__fixture__/ppq203.json
{
"@context": [
   "https://www.w3.org/2018/credentials/v1",
   "https://w3id.org/traceability/v1"
 ],
 "id": "https://example.com/credentials/123",
 "type": ["VerifiableCredential"],
 "issuanceDate": "2021-02-04T20:29:37+00:00",
 "issuer": "did:example:123",
"credentialSubject": {
   "type": "ppq203",
   "facility": {
      "type": "Place",
      "globalLocationNumber": "2835034258350",
      "geo": {
         "type": "GeoCoordinates",
         "latitude": "38.8303",
         "longitude": "135.2572"
      },
      "address": {
         "type": "PostalAddress",
         "organizationName": "Mann LLC",
         "streetAddress": "6074 Kemmer Summit",
         "addressLocality": "North Carrieview",
         "addressRegion": "Indiana",
         "postalCode": "96474-7026",
         "addressCountry": "USA"
      }
   },
   "inspector": {
      "type": "Inspector",
      "person": {
         "type": "Person",
         "firstName": "May",
         "lastName": "Hane",
         "email": "Devante.Hauck@example.net",
         "phoneNumber": "555-734-8303",
         "worksFor": {
            "type": "Organization",
            "name": "Cassin Inc",
            "description": "Providing good inspections",
            "address": {
               "type": "PostalAddress",
               "streetAddress": "20355 Cordia Spurs",
               "addressLocality": "Port Bridgetport",
               "addressRegion": "Hawaii",
               "postalCode": "57015",
               "addressCountry": "USA"
            },
            "email": "Zion34@example.com",
            "phoneNumber": "555-810-8218",
            "faxNumber": "555-536-5446"
         },
         "jobTitle": "Director of Food Inspections"
      },
      "qualification": [
         {
            "type": "Qualification",
            "qualificationCategory": "Central Inspection Officer",
            "qualificationValue": "Facilitator"
         }
      ]
   },
   "shipment": {
      "type": "ParcelDelivery",
      "deliveryAddress": {
         "type": "PostalAddress",
         "organizationName": "Auer, Ernser and Thompson",
         "streetAddress": "282 Noe Village",
         "addressLocality": "West Candelarioton",
         "addressRegion": "Oregon",
         "postalCode": "91758-6895",
         "addressCountry": "USA"
      },
      "originAddress": {
         "type": "PostalAddress",
         "organizationName": "Bosco - Nolan",
         "streetAddress": "87881 Windler Drives",
         "addressLocality": "Port Dejamouth",
         "addressRegion": "Utah",
         "postalCode": "17543",
         "addressCountry": "USA"
      },
      "deliveryMethod": "Truck transport",
      "trackingNumber": "613770897867"
   },
   "applicant": {
      "type": "Person",
      "firstName": "Freddy",
      "lastName": "Bode",
      "email": "Uriel_Kuhic@example.org",
      "phoneNumber": "555-148-7393",
      "worksFor": {
         "type": "Organization",
         "name": "Sanford Inc",
         "description": "Providing food inspections",
         "address": {
            "type": "PostalAddress",
            "streetAddress": "6948 Alfonso Falls",
            "addressLocality": "East Desmondmouth",
            "addressRegion": "Rhode Island",
            "postalCode": "36187",
            "addressCountry": "USA"
         },
         "email": "Levi.Corwin89@example.net",
         "phoneNumber": "555-229-6464",
         "faxNumber": "555-248-7097"
      },
      "jobTitle": "National Optimization Analyst"
   },
   "inspectionDate": "2020-03-15",
   "inspectionType": "Food Safety",
   "observation": [
      {
         "type": "Observation",
         "property": {
            "type": "ChemicalProperty",
            "name": "Americium",
            "formula": "Am",
            "inchi": "InChI=1S/Am",
            "inchikey": "LXQXZNRPTYVCNG-UHFFFAOYSA-N"
         },
         "measurement": {
            "type": "MeasuredValue",
            "value": "40.794",
            "unitCode": "P1"
         }
      },
      {
         "type": "Observation",
         "property": {
            "type": "ChemicalProperty",
            "name": "Dysprosium",
            "formula": "Dy",
            "inchi": "InChI=1S/Dy",
            "inchikey": "KBQHZAAAGSGFKK-UHFFFAOYSA-N"
         },
         "measurement": {
            "type": "MeasuredValue",
            "value": "59.206",
            "unitCode": "P1"
         }
      }
   ],
   "certificateNumber": "283728361115",
   "carrierId": "797385833528",
   "signatureDate": "2021-02-16"
}

}

=== w3c-ccg/traceability-vocab/packages/generate-examples/src/__fixture__/entity.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": ["VerifiableCredential"],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": "did:example:123",
   "credentialSubject": {
      "id": "did:example:123",
      "type": "Organization",
      "name": "California Avocados Direct",
      "description": "Fourth generation family avocado farm",
      "address": {
         "type": "PostalAddress",
         "streetAddress": "9700 Circle R Dr,",
         "addressLocality": "Escondido",
         "addressRegion": "California",
         "postalCode": "92026",
         "addressCountry": "USA"
      },
      "email": "Chase97@example.com",
      "phoneNumber": "555-187-9457"
   }
}
