=== w3c-ccg/traceability-vocab/packages/traceability-schemas/schemas/Observation.json
{
  "$id": "https://w3id.org/traceability/schemas/Observation.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"Observation\", \"@id\": \"https://schema.org/Observation\"}",
  "title": "Observation",
  "description": "Instances of the class Observation are used to specify observations about an entity at a particular time.",
  "type": "object",
  "properties": {
    "@context": {
      "type": "array"
    },
    "type": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array"
        }
      ]
    },
    "property": {
      "$comment": "{\"term\": \"property\", \"@id\": \"https://schema.org/measuredProperty\"}",
      "title": "Measured Property",
      "description": "The property of an Observation.",
      "$ref": "https://w3id.org/traceability/schemas/MeasuredProperty.json"
    },
    "measurement": {
      "$comment": "{\"term\": \"measurement\", \"@id\": \"https://w3id.org/traceability#MeasuredValue\"}",
      "title": "Measured Value",
      "description": "The measurement of an Observation.",
      "$ref": "https://w3id.org/traceability/schemas/MeasuredValue.json"
    },
    "date": {
      "$comment": "{\"term\": \"date\", \"@id\": \"https://schema.org/observationDate\"}",
      "title": "Observation Date",
      "description": "The date of the Observation.",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "examples": []
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/Observation/good.json
[
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "Observation",
    "property": {
      "type": "MechanicalProperty",
      "identifier": "ISO 180",
      "name": "Izod Impact Strength Test",
      "description": "ISO 180 defines the method used for pendulums to determine the impact resistance of a plastic specimen when supported in a cantilever configuration. Test results are used to evaluate the resilience of materials, typically plastics."
    },
    "measurement": {
      "type": "MeasuredValue",
      "value": "22.493",
      "unitCode": "B13"
    }
  },
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "Observation",
    "property": {
      "type": "MechanicalProperty",
      "identifier": "ISO 180",
      "name": "Izod Impact Strength Test",
      "description": "ISO 180 defines the method used for pendulums to determine the impact resistance of a plastic specimen when supported in a cantilever configuration. Test results are used to evaluate the resilience of materials, typically plastics."
    },
    "measurement": {
      "type": "MeasuredValue",
      "value": "56.603",
      "unitCode": "B13"
    }
  },
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "Observation",
    "property": {
      "type": "MechanicalProperty",
      "identifier": "ISO 1352",
      "name": "Torque-controlled fatigue testing",
      "description": "ISO 1352:2011 specifies the conditions for performing torsional, constant-amplitude, nominally elastic stress fatigue tests on metallic specimens without deliberately introducing stress concentrations. The tests are carried out at ambient temperature (ideally at between 10 °C and 35 °C) in air by applying a pure couple to the specimen about its longitudinal axis."
    },
    "measurement": {
      "type": "MeasuredValue",
      "value": "00.00",
      "unitCode": "UNKNOWN"
    }
  }
]
