=== w3c-ccg/traceability-vocab/packages/traceability-schemas/schemas/Organization.json
{
  "$id": "https://w3id.org/traceability/schemas/Organization.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"Organization\", \"@id\": \"https://schema.org/Organization\"}",
  "title": "Organization",
  "description": "An organization such as a corporation, firm, club, etc.",
  "type": "object",
  "properties": {
    "@context": {
      "type": "array"
    },
    "type": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array"
        }
      ]
    },
    "name": {
      "$comment": "{\"term\": \"name\", \"@id\": \"https://schema.org/name\"}",
      "title": "Name",
      "description": "Name of the organization.",
      "type": "string"
    },
    "leiCode": {
      "$comment": "{\"term\": \"leiCode\", \"@id\": \"https://schema.org/leiCode\"}",
      "title": "Legal Entity Identifier Code",
      "description": "Legal entity identifier code",
      "type": "string"
    },
    "url": {
      "$comment": "{\"term\": \"url\", \"@id\": \"https://schema.org/url\"}",
      "title": "URL",
      "description": "URL of the organization.",
      "type": "string"
    },
    "description": {
      "$comment": "{\"term\": \"description\", \"@id\": \"https://schema.org/description\"}",
      "title": "Description",
      "description": "Description of the company.",
      "type": "string"
    },
    "globalLocationNumber": {
      "$comment": "{\"term\": \"globalLocationNumber\", \"@id\": \"https://schema.org/globalLocationNumber\"}",
      "title": "Global Location Number",
      "description": "The GS1 GLN of the organization.",
      "type": "string"
    },
    "address": {
      "$comment": "{\"term\": \"address\", \"@id\": \"https://schema.org/PostalAddress\"}",
      "title": "Postal Address",
      "description": "The postal address for an organization or place.",
      "$ref": "https://w3id.org/traceability/schemas/PostalAddress.json"
    },
    "email": {
      "$comment": "{\"term\": \"email\", \"@id\": \"https://schema.org/email\"}",
      "title": "Email Address",
      "description": "Organization's primary email address.",
      "type": "string"
    },
    "phoneNumber": {
      "$comment": "{\"term\": \"phoneNumber\", \"@id\": \"https://schema.org/telephone\"}",
      "title": "Phone Number",
      "description": "Organization's contact phone number.",
      "type": "string"
    },
    "faxNumber": {
      "$comment": "{\"term\": \"faxNumber\", \"@id\": \"https://schema.org/faxNumber\"}",
      "title": "Phone Number",
      "description": "Organization's fax number.",
      "type": "string"
    },
    "brand": {
      "$comment": "{\"term\": \"brand\", \"@id\": \"https://schema.org/Brand\"}",
      "title": "Brand",
      "description": "Branding for this organization",
      "$ref": "https://w3id.org/traceability/schemas/Brand.json"
    },
    "contactPoint": {
      "$comment": "{\"term\": \"contactPoint\", \"@id\": \"https://schema.org/ContactPoint\"}",
      "title": "Contact Point",
      "description": "Points of contact for this organization",
      "$ref": "https://w3id.org/traceability/schemas/ContactPoint.json"
    }
  },
  "additionalProperties": false,
  "examples": []
}

=== w3c-ccg/traceability-vocab/packages/traceability-schemas/src/__fixtures__/ContactPoint/good.json
[
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "ContactPoint",
    "name": "Christiansen - Glover",
    "address": {
      "type": "PostalAddress",
      "streetAddress": "7072 Sonny Pike",
      "addressLocality": "New Rogerview",
      "addressRegion": "Alabama",
      "postalCode": "29703",
      "addressCountry": "Ukraine"
    },
    "email": "Rory57@example.com",
    "phoneNumber": "555-191-8440"
  },
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "ContactPoint",
    "name": "Glover Inc",
    "address": {
      "type": "PostalAddress",
      "streetAddress": "9687 Conn Ranch",
      "addressLocality": "East Metahaven",
      "addressRegion": "North Dakota",
      "postalCode": "92719",
      "addressCountry": "Pakistan"
    },
    "email": "Oswald_Nicolas@example.com",
    "phoneNumber": "555-732-9495"
  },
  {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": "ContactPoint",
    "name": "Pagac, Romaguera and Mohr",
    "address": {
      "type": "PostalAddress",
      "streetAddress": "26373 Stokes Alley",
      "addressLocality": "Denesikbury",
      "addressRegion": "Nevada",
      "postalCode": "48723-6847",
      "addressCountry": "Tanzania"
    },
    "email": "Eleazar93@example.org",
    "phoneNumber": "555-682-2941"
  }
]
